# this will test the downloader script for MagPI which is called by:
# The MagPi
#   The MagPi regular issues (Mac/Linux)
#   The Magpi books / special issues (Mac/Linux/Win)
# Hello World
#   Hello World regular issues  (Mac/Linux)
#   Hello World books (Mac/Linux/Win)
# HackSpace Magazine
#   Hackspace Magazine regular issues
#   Hackspace Magazine books (Mac/Linux/Win)
# Wireframe
#   Wireframe regular issues (Mac/Linux)
#   Wireframe books (Mac/Linux/Win)


name: Testing MagPi Books

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  books-powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.6

      - name: make folder for books
        run: mkdir books
        shell: bash

      - name: Download Books MagPi windows
        id: MagPiBooksWin
        shell: pwsh
        run: ./windows/downloader.ps1 -downloadUrl "https://magpi.raspberrypi.com/books/projects-5/pdf/download" -outputDir "books"

      - name: "Check file existence Windows special"
        id: check_files
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: "books/Pi-Projects5.pdf"
          fail: true

      - name: lslah books
        run: Get-ChildItem –path D:\a\downloader\downloader\books

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1

  books-bash-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6

      - name: make folder for books
        run: mkdir books

      - name: Download books linux
        id: bookIssues
        run: bash ./linux_mac/downloader.sh https://magpi.raspberrypi.com/books/projects-5/pdf/download books

      - name: lslah
        run: ls -lah books/

      - name: "Check file existence Linux special issues"
        id: check_files
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: "books/Pi-Projects5.pdf"
          fail: true

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1

  special-bash-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.1.6

      - name: make folder for books
        run: mkdir books

      - name: Download books macos
        id: bookIssuesMac
        run: bash ./linux_mac/downloader.sh https://magpi.raspberrypi.com/books/projects-5/pdf/download books

      - name: lslah
        run: ls -lah books/

      - name: "Check file existence mac special issues"
        id: check_files
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: "books/Pi-Projects5.pdf"
          fail: true

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1
