# this will test the downloader script for MagPI which is called by:
# The MagPi
#   The MagPi regular issues (Mac/Linux)
#   The Magpi books / special issues (Mac/Linux/Win)
# Hello World
#   Hello World regular issues  (Mac/Linux)
#   Hello World books (Mac/Linux/Win)
# HackSpace Magazine
#   Hackspace Magazine regular issues
#   Hackspace Magazine books (Mac/Linux/Win)
# Wireframe
#   Wireframe regular issues (Mac/Linux)
#   Wireframe books (Mac/Linux/Win)


name: Testing MagPi Books

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  magpi-books:
    strategy:
      matrix:
        os: [ macos, ubuntu, windows ]
      fail-fast: false # Allows to see results from other combinations
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Set OS-specific variables for Windows
        if: matrix.os == 'windows'
        run: |
          echo "OS_PATH=windows" >> $GITHUB_ENV
          echo "OS_FILE_EXTENSION=ps1" >> $GITHUB_ENV
        shell: bash

      - name: Set OS-specific variables for macOS and Ubuntu
        if: matrix.os != 'windows'
        run: |
          echo "OS_PATH=linux_mac" >> $GITHUB_ENV
          echo "OS_FILE_EXTENSION=sh" >> $GITHUB_ENV
        shell: bash

      - name: Download Books MagPi windows
        id: MagPiBooksWin
        run: ./${{ env.OS_PATH }}/downloader.${{ env.OS_FILE_EXTENSION }} -downloadUrl "https://magpi.raspberrypi.com/books/projects-5/pdf/download" -outputDir "books"

      - name: "Check file existence Windows special"
        id: check_files
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
        with:
          files: "books/Pi-Projects5.pdf"
          fail: true

      - name: lslah books
        run: Get-ChildItem –path D:\a\downloader\downloader\books

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1

