## this will test the downloader script for Wireframe which is called by:
## The MagPi
##   The MagPi regular issues (Mac/Linux)
##   The Magpi books / special issues (Mac/Linux/Win)
## Hello World
##   Hello World regular issues  (Mac/Linux)download the correct files
##   Hello World books (Mac/Linux/Win)
## HackSpace Magazine
##   Hackspace Magazine regular issues
##   Hackspace Magazine books (Mac/Linux/Win)
## Wireframe
##   Wireframe regular issues (Mac/Linux)
##   Wireframe books (Mac/Linux/Win)
#
#
#name: Testing Wireframe Books
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
## A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
#  books-powershell:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v3.4.0
#
#      - name: make folder for books
#        run: mkdir books
#        shell: bash
#
#      - name: Download Books Wireframe windows
#        id: WireframeBooksWin
#        shell: pwsh
#        run: ./windows/downloader.ps1 -downloadUrl "https://wireframe.raspberrypi.com/books/computers-that-made-britain/pdf" -outputDir "books"
#
#      - name: lslah books
#        run: Get-ChildItem –path D:\a\downloader\downloader\books
#
#      - name: "Check file existence Windows special"
#        id: check_files
#        uses: andstor/file-existence-action@v2.0.0
#        with:
#          files: "books/Computers%20that%20made%20Britain%20v1.pdf"
#          fail: true
#
#      - name: File exists
#        if: steps.check_files.outputs.files_exists == 'false'
#        run: exit 1
#
#  books-bash-linux:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3.4.0
#
#      - name: make folder for books
#        run: mkdir books
#
#      - name: Download books linux
#        id: bookIssues
#        run: bash ./linux_mac/downloader.sh https://wireframe.raspberrypi.com/books/computers-that-made-britain/pdf books
#
#      - name: lslah
#        run: ls -lah books/
#
#      - name: "Check file existence Linux special issues"
#        id: check_files
#        uses: andstor/file-existence-action@v2.0.0
#        with:
#          files: "books/Computers that made Britain v1.pdf"
#          fail: true
#
#      - name: File exists
#        if: steps.check_files.outputs.files_exists == 'false'
#        run: exit 1
#
#  special-bash-macos:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v3.4.0
#
#      - name: make folder for books
#        run: mkdir books
#
#      - name: Download books macos
#        id: bookIssuesMac
#        run: bash ./linux_mac/downloader.sh https://wireframe.raspberrypi.com/books/computers-that-made-britain/pdf books
#
#      - name: lslah
#        run: ls -lah books/
#
#      - name: "Check file existence mac special issues"
#        id: check_files
#        uses: andstor/file-existence-action@v2.0.0
#        with:
#          files: "books/Computers that made Britain v1.pdf"
#          fail: true
#
#      - name: File exists
#        if: steps.check_files.outputs.files_exists == 'false'
#        run: exit 1
